EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/hifi4dsp/hifi4dsp_spi

ccflags-y += -I$(srctree)/drivers/mstar2/drv/hifi4dsp/hifi4dsp_audio_ipi/common/framework

obj-y += adsp_ipi.o
obj-y += adsp_ipi_platform.o
obj-y += acs_audio_ipc_hwio.o
