/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly 
#ifndef _MT5871IYYTYY_H_
#define _MT5871IYYTYY_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_C19 PAD_PWM2
#define PAD_PWM2 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_C19_IS_GPIO
#define BALL_C19_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_C19_IS_GPIO
#endif 

#define BALL_C13 PAD_TCON0
#define PAD_TCON0 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif 
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO BALL_C13_IS_GPIO
#endif 

#define BALL_C17 PAD_PWM1
#define PAD_PWM1 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_C17_IS_GPIO
#define BALL_C17_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_C17_IS_GPIO
#endif 

#define BALL_A14 PAD_TCON1
#define PAD_TCON1 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_A14_IS_GPIO
#define BALL_A14_IS_GPIO 0
#endif 
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO BALL_A14_IS_GPIO
#endif 

#define BALL_A19 PAD_PWM0
#define PAD_PWM0 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_A19_IS_GPIO
#define BALL_A19_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_A19_IS_GPIO
#endif 

#define BALL_B14 PAD_TCON2
#define PAD_TCON2 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif 
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO BALL_B14_IS_GPIO
#endif 

#define BALL_C18 PAD_MIC_SD0
#define PAD_MIC_SD0 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_C18_IS_GPIO
#define BALL_C18_IS_GPIO 0
#endif 
#ifndef PAD_MIC_SD0_IS_GPIO
#define PAD_MIC_SD0_IS_GPIO BALL_C18_IS_GPIO
#endif 

#define BALL_B19 PAD_MIC_SD2
#define PAD_MIC_SD2 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_B19_IS_GPIO
#define BALL_B19_IS_GPIO 0
#endif 
#ifndef PAD_MIC_SD2_IS_GPIO
#define PAD_MIC_SD2_IS_GPIO BALL_B19_IS_GPIO
#endif 

#define BALL_C14 PAD_TCON3
#define PAD_TCON3 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif 
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO BALL_C14_IS_GPIO
#endif 

#define BALL_B17 PAD_MIC_BCK
#define PAD_MIC_BCK 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_B17_IS_GPIO
#define BALL_B17_IS_GPIO 0
#endif 
#ifndef PAD_MIC_BCK_IS_GPIO
#define PAD_MIC_BCK_IS_GPIO BALL_B17_IS_GPIO
#endif 

#define BALL_B15 PAD_TCON4
#define PAD_TCON4 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif 
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO BALL_B15_IS_GPIO
#endif 

#define BALL_B18 PAD_MIC_SD1
#define PAD_MIC_SD1 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_B18_IS_GPIO
#define BALL_B18_IS_GPIO 0
#endif 
#ifndef PAD_MIC_SD1_IS_GPIO
#define PAD_MIC_SD1_IS_GPIO BALL_B18_IS_GPIO
#endif 

#define BALL_E18 PAD_GPIO0
#define PAD_GPIO0 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_E18_IS_GPIO
#define BALL_E18_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_E18_IS_GPIO
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define BALL_B20 PAD_DDCR_CK
#define PAD_DDCR_CK 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_B20_IS_GPIO
#define BALL_B20_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_B20_IS_GPIO
#endif 

#define BALL_A20 PAD_DDCR_DA
#define PAD_DDCR_DA 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_A20_IS_GPIO
#define BALL_A20_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_A20_IS_GPIO
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define BALL_AD16 PAD_GPIO9
#define PAD_GPIO9 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_AD16_IS_GPIO
#define BALL_AD16_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_AD16_IS_GPIO
#endif 

#define BALL_AC16 PAD_GPIO10
#define PAD_GPIO10 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO BALL_AC16_IS_GPIO
#endif 

#define BALL_M3 PAD_GPIO11
#define PAD_GPIO11 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_M3_IS_GPIO
#define BALL_M3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO BALL_M3_IS_GPIO
#endif 

#define BALL_L3 PAD_GPIO12
#define PAD_GPIO12 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_L3_IS_GPIO
#endif 

#define BALL_E14 PAD_LD_SPI_MISO
#define PAD_LD_SPI_MISO 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_E14_IS_GPIO
#define BALL_E14_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_MISO_IS_GPIO
#define PAD_LD_SPI_MISO_IS_GPIO BALL_E14_IS_GPIO
#endif 

#define BALL_D17 PAD_LD_SPI_CS
#define PAD_LD_SPI_CS 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_D17_IS_GPIO
#define BALL_D17_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_CS_IS_GPIO
#define PAD_LD_SPI_CS_IS_GPIO BALL_D17_IS_GPIO
#endif 

#define BALL_E17 PAD_LD_SPI_MOSI
#define PAD_LD_SPI_MOSI 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_MOSI_IS_GPIO
#define PAD_LD_SPI_MOSI_IS_GPIO BALL_E17_IS_GPIO
#endif 

#define BALL_D14 PAD_LD_SPI_CK
#define PAD_LD_SPI_CK 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_D14_IS_GPIO
#define BALL_D14_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_CK_IS_GPIO
#define PAD_LD_SPI_CK_IS_GPIO BALL_D14_IS_GPIO
#endif 

#define PAD_DIM0 9999
#ifndef PAD_DIM0_IS_GPIO
#define PAD_DIM0_IS_GPIO 0
#endif 

#define PAD_DIM1 9999
#ifndef PAD_DIM1_IS_GPIO
#define PAD_DIM1_IS_GPIO 0
#endif 

#define PAD_DIM2 9999
#ifndef PAD_DIM2_IS_GPIO
#define PAD_DIM2_IS_GPIO 0
#endif 

#define PAD_DIM3 9999
#ifndef PAD_DIM3_IS_GPIO
#define PAD_DIM3_IS_GPIO 0
#endif 

#define BALL_L2 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_L2_IS_GPIO
#define BALL_L2_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_L2_IS_GPIO
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define BALL_L1 PAD_SPDIF_IN
#define PAD_SPDIF_IN 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_L1_IS_GPIO
#define BALL_L1_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_L1_IS_GPIO
#endif 

#define BALL_K6 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_K6_IS_GPIO
#define BALL_K6_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_K6_IS_GPIO
#endif 

#define BALL_L5 PAD_I2S_IN_DIN2
#define PAD_I2S_IN_DIN2 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_DIN2_IS_GPIO
#define PAD_I2S_IN_DIN2_IS_GPIO BALL_L5_IS_GPIO
#endif 

#define BALL_K7 PAD_I2S_IN_DIN0
#define PAD_I2S_IN_DIN0 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_K7_IS_GPIO
#define BALL_K7_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_DIN0_IS_GPIO
#define PAD_I2S_IN_DIN0_IS_GPIO BALL_K7_IS_GPIO
#endif 

#define BALL_L4 PAD_I2S_IN_DIN1
#define PAD_I2S_IN_DIN1 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_DIN1_IS_GPIO
#define PAD_I2S_IN_DIN1_IS_GPIO BALL_L4_IS_GPIO
#endif 

#define BALL_K5 PAD_I2S_IN_WCK
#define PAD_I2S_IN_WCK 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WCK_IS_GPIO
#define PAD_I2S_IN_WCK_IS_GPIO BALL_K5_IS_GPIO
#endif 

#define BALL_H2 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_H2_IS_GPIO
#endif 

#define BALL_K2 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_K2_IS_GPIO
#endif 

#define BALL_J2 PAD_I2S_OUT_SD0
#define PAD_I2S_OUT_SD0 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO BALL_J2_IS_GPIO
#endif 

#define BALL_J3 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_J3_IS_GPIO
#endif 

#define BALL_K4 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_K4_IS_GPIO
#define BALL_K4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_K4_IS_GPIO
#endif 

#define BALL_K3 PAD_I2S_OUT_WCK
#define PAD_I2S_OUT_WCK 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WCK_IS_GPIO
#define PAD_I2S_OUT_WCK_IS_GPIO BALL_K3_IS_GPIO
#endif 

#define BALL_V5 PAD_PWM_PM
#define PAD_PWM_PM 5
#define GPIO_PAD_5 GPIO04
#ifndef BALL_V5_IS_GPIO
#define BALL_V5_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_V5_IS_GPIO
#endif 

#define BALL_AH3 PAD_GPIO0_PM
#define PAD_GPIO0_PM 7
#define GPIO_PAD_7 GPIO06
#ifndef BALL_AH3_IS_GPIO
#define BALL_AH3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_PM_IS_GPIO
#define PAD_GPIO0_PM_IS_GPIO BALL_AH3_IS_GPIO
#endif 

#define BALL_P4 PAD_USB_CTRL
#define PAD_USB_CTRL 10
#define GPIO_PAD_10 GPIO09
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif 
#ifndef PAD_USB_CTRL_IS_GPIO
#define PAD_USB_CTRL_IS_GPIO BALL_P4_IS_GPIO
#endif 

#define BALL_N2 PAD_GPIO1_PM
#define PAD_GPIO1_PM 8
#define GPIO_PAD_8 GPIO07
#ifndef BALL_N2_IS_GPIO
#define BALL_N2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_PM_IS_GPIO
#define PAD_GPIO1_PM_IS_GPIO BALL_N2_IS_GPIO
#endif 

#define BALL_J4 PAD_DDCA_CK
#define PAD_DDCA_CK 2
#define GPIO_PAD_2 GPIO01
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_J4_IS_GPIO
#endif 

#define BALL_M2 PAD_GPIO2_PM
#define PAD_GPIO2_PM 9
#define GPIO_PAD_9 GPIO08
#ifndef BALL_M2_IS_GPIO
#define BALL_M2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_PM_IS_GPIO
#define PAD_GPIO2_PM_IS_GPIO BALL_M2_IS_GPIO
#endif 

#define BALL_J5 PAD_DDCA_DA
#define PAD_DDCA_DA 3
#define GPIO_PAD_3 GPIO02
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define BALL_R2 PAD_GPIO5_PM
#define PAD_GPIO5_PM 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_R2_IS_GPIO
#define BALL_R2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_PM_IS_GPIO
#define PAD_GPIO5_PM_IS_GPIO BALL_R2_IS_GPIO
#endif 

#define BALL_N3 PAD_IRIN
#define PAD_IRIN 4
#define GPIO_PAD_4 GPIO03
#ifndef BALL_N3_IS_GPIO
#define BALL_N3_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_N3_IS_GPIO
#endif 

#define BALL_AC4 PAD_GPIO6_PM
#define PAD_GPIO6_PM 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_PM_IS_GPIO
#define PAD_GPIO6_PM_IS_GPIO BALL_AC4_IS_GPIO
#endif 

#define BALL_U2 PAD_GPIO7_PM
#define PAD_GPIO7_PM 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_U2_IS_GPIO
#define BALL_U2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_PM_IS_GPIO
#define PAD_GPIO7_PM_IS_GPIO BALL_U2_IS_GPIO
#endif 

#define BALL_AB4 PAD_GPIO8_PM
#define PAD_GPIO8_PM 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_PM_IS_GPIO
#define PAD_GPIO8_PM_IS_GPIO BALL_AB4_IS_GPIO
#endif 

#define BALL_M1 PAD_GPIO9_PM
#define PAD_GPIO9_PM 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_M1_IS_GPIO
#define BALL_M1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_PM_IS_GPIO
#define PAD_GPIO9_PM_IS_GPIO BALL_M1_IS_GPIO
#endif 

#define BALL_Y3 PAD_GPIO10_PM
#define PAD_GPIO10_PM 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_Y3_IS_GPIO
#define BALL_Y3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_PM_IS_GPIO
#define PAD_GPIO10_PM_IS_GPIO BALL_Y3_IS_GPIO
#endif 

#define BALL_H1 PAD_GPIO11_PM
#define PAD_GPIO11_PM 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_H1_IS_GPIO
#define BALL_H1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_PM_IS_GPIO
#define PAD_GPIO11_PM_IS_GPIO BALL_H1_IS_GPIO
#endif 

#define BALL_M4 PAD_GPIO12_PM
#define PAD_GPIO12_PM 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_PM_IS_GPIO
#define PAD_GPIO12_PM_IS_GPIO BALL_M4_IS_GPIO
#endif 

#define PAD_WOL_INT_OUT 9999
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO 0
#endif 

#define BALL_AD11 PAD_DDCDA_CK
#define PAD_DDCDA_CK 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_AD11_IS_GPIO
#define BALL_AD11_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_AD11_IS_GPIO
#endif 

#define PAD_GPIO13_PM 9999
#ifndef PAD_GPIO13_PM_IS_GPIO
#define PAD_GPIO13_PM_IS_GPIO 0
#endif 

#define BALL_AD12 PAD_DDCDA_DA
#define PAD_DDCDA_DA 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_AD12_IS_GPIO
#define BALL_AD12_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_AD12_IS_GPIO
#endif 

#define PAD_GPIO14_PM 9999
#ifndef PAD_GPIO14_PM_IS_GPIO
#define PAD_GPIO14_PM_IS_GPIO 0
#endif 

#define BALL_AC13 PAD_DDCDB_CK
#define PAD_DDCDB_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_AC13_IS_GPIO
#define BALL_AC13_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_AC13_IS_GPIO
#endif 

#define PAD_GPIO15_PM 9999
#ifndef PAD_GPIO15_PM_IS_GPIO
#define PAD_GPIO15_PM_IS_GPIO 0
#endif 

#define BALL_AD13 PAD_DDCDB_DA
#define PAD_DDCDB_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_AD13_IS_GPIO
#define BALL_AD13_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_AD13_IS_GPIO
#endif 

#define PAD_GPIO16_PM 9999
#ifndef PAD_GPIO16_PM_IS_GPIO
#define PAD_GPIO16_PM_IS_GPIO 0
#endif 

#define BALL_W7 PAD_DDCDC_CK
#define PAD_DDCDC_CK 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_W7_IS_GPIO
#define BALL_W7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_W7_IS_GPIO
#endif 

#define PAD_GPIO17_PM 9999
#ifndef PAD_GPIO17_PM_IS_GPIO
#define PAD_GPIO17_PM_IS_GPIO 0
#endif 

#define BALL_V7 PAD_DDCDC_DA
#define PAD_DDCDC_DA 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_V7_IS_GPIO
#define BALL_V7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_V7_IS_GPIO
#endif 

#define PAD_GPIO18_PM 9999
#ifndef PAD_GPIO18_PM_IS_GPIO
#define PAD_GPIO18_PM_IS_GPIO 0
#endif 

#define BALL_W5 PAD_DDCDD_CK
#define PAD_DDCDD_CK 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_W5_IS_GPIO
#define BALL_W5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_W5_IS_GPIO
#endif 

#define PAD_GPIO19_PM 9999
#ifndef PAD_GPIO19_PM_IS_GPIO
#define PAD_GPIO19_PM_IS_GPIO 0
#endif 

#define BALL_W6 PAD_DDCDD_DA
#define PAD_DDCDD_DA 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_W6_IS_GPIO
#define BALL_W6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_W6_IS_GPIO
#endif 

#define PAD_GPIO20_PM 9999
#ifndef PAD_GPIO20_PM_IS_GPIO
#define PAD_GPIO20_PM_IS_GPIO 0
#endif 

#define PAD_GPIO26_PM 9999
#ifndef PAD_GPIO26_PM_IS_GPIO
#define PAD_GPIO26_PM_IS_GPIO 0
#endif 

#define PAD_GPIO21_PM 9999
#ifndef PAD_GPIO21_PM_IS_GPIO
#define PAD_GPIO21_PM_IS_GPIO 0
#endif 

#define PAD_GPIO27_PM 9999
#ifndef PAD_GPIO27_PM_IS_GPIO
#define PAD_GPIO27_PM_IS_GPIO 0
#endif 

#define PAD_GPIO22_PM 9999
#ifndef PAD_GPIO22_PM_IS_GPIO
#define PAD_GPIO22_PM_IS_GPIO 0
#endif 

#define PAD_GPIO28_PM 9999
#ifndef PAD_GPIO28_PM_IS_GPIO
#define PAD_GPIO28_PM_IS_GPIO 0
#endif 

#define PAD_GPIO23_PM 9999
#ifndef PAD_GPIO23_PM_IS_GPIO
#define PAD_GPIO23_PM_IS_GPIO 0
#endif 

#define BALL_U5 PAD_VID0
#define PAD_VID0 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_U5_IS_GPIO
#define BALL_U5_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_U5_IS_GPIO
#endif 

#define PAD_GPIO24_PM 9999
#ifndef PAD_GPIO24_PM_IS_GPIO
#define PAD_GPIO24_PM_IS_GPIO 0
#endif 

#define BALL_P7 PAD_VID1
#define PAD_VID1 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_P7_IS_GPIO
#define BALL_P7_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_P7_IS_GPIO
#endif 

#define PAD_GPIO25_PM 9999
#ifndef PAD_GPIO25_PM_IS_GPIO
#define PAD_GPIO25_PM_IS_GPIO 0
#endif 

#define BALL_P3 PAD_VID2
#define PAD_VID2 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_P3_IS_GPIO
#define BALL_P3_IS_GPIO 0
#endif 
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO BALL_P3_IS_GPIO
#endif 

#define BALL_AD14 PAD_CEC0
#define PAD_CEC0 6
#define GPIO_PAD_6 GPIO05
#ifndef BALL_AD14_IS_GPIO
#define BALL_AD14_IS_GPIO 0
#endif 
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_AD14_IS_GPIO
#endif 

#define BALL_AC5 PAD_SAR0
#define PAD_SAR0 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_AC5_IS_GPIO
#define BALL_AC5_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_AC5_IS_GPIO
#endif 

#define BALL_Y8 PAD_SAR1
#define PAD_SAR1 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_Y8_IS_GPIO
#define BALL_Y8_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_Y8_IS_GPIO
#endif 

#define BALL_AC9 PAD_SAR2
#define PAD_SAR2 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_AC9_IS_GPIO
#define BALL_AC9_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_AC9_IS_GPIO
#endif 

#define BALL_AB9 PAD_SAR3
#define PAD_SAR3 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_AB9_IS_GPIO
#define BALL_AB9_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_AB9_IS_GPIO
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define BALL_H5 PAD_VPLUGIN
#define PAD_VPLUGIN 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif 
#ifndef PAD_VPLUGIN_IS_GPIO
#define PAD_VPLUGIN_IS_GPIO BALL_H5_IS_GPIO
#endif 

#define PAD_SAR6 9999
#ifndef PAD_SAR6_IS_GPIO
#define PAD_SAR6_IS_GPIO 0
#endif 

#define PAD_SAR7 9999
#ifndef PAD_SAR7_IS_GPIO
#define PAD_SAR7_IS_GPIO 0
#endif 

#define BALL_AB11 PAD_TGPIO3
#define PAD_TGPIO3 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AB11_IS_GPIO
#define BALL_AB11_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AB11_IS_GPIO
#endif 

#define BALL_AC11 PAD_TGPIO2
#define PAD_TGPIO2 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_AC11_IS_GPIO
#define BALL_AC11_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AC11_IS_GPIO
#endif 

#define PAD_TGPIO1 9999
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO 0
#endif 

#define PAD_TGPIO0 9999
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO 0
#endif 

#define PAD_TS3_D0 9999
#ifndef PAD_TS3_D0_IS_GPIO
#define PAD_TS3_D0_IS_GPIO 0
#endif 

#define PAD_TS3_VLD 9999
#ifndef PAD_TS3_VLD_IS_GPIO
#define PAD_TS3_VLD_IS_GPIO 0
#endif 

#define PAD_TS3_SYNC 9999
#ifndef PAD_TS3_SYNC_IS_GPIO
#define PAD_TS3_SYNC_IS_GPIO 0
#endif 

#define PAD_TS3_CLK 9999
#ifndef PAD_TS3_CLK_IS_GPIO
#define PAD_TS3_CLK_IS_GPIO 0
#endif 

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif 

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif 

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif 

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif 

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif 

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif 

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif 

#define BALL_AG17 PAD_TS2_D0
#define PAD_TS2_D0 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AG17_IS_GPIO
#define BALL_AG17_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_AG17_IS_GPIO
#endif 

#define BALL_AF17 PAD_TS2_VLD
#define PAD_TS2_VLD 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_AF17_IS_GPIO
#define BALL_AF17_IS_GPIO 0
#endif 
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_AF17_IS_GPIO
#endif 

#define BALL_AH17 PAD_TS2_SYNC
#define PAD_TS2_SYNC 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_AH17_IS_GPIO
#define BALL_AH17_IS_GPIO 0
#endif 
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_AH17_IS_GPIO
#endif 

#define BALL_AH18 PAD_TS2_CLK
#define PAD_TS2_CLK 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_AH18_IS_GPIO
#define BALL_AH18_IS_GPIO 0
#endif 
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_AH18_IS_GPIO
#endif 

#define BALL_AD18 PAD_PCM2_WAIT_N
#define PAD_PCM2_WAIT_N 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_AD18_IS_GPIO
#define BALL_AD18_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO BALL_AD18_IS_GPIO
#endif 

#define BALL_AE18 PAD_PCM2_RESET
#define PAD_PCM2_RESET 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_AE18_IS_GPIO
#define BALL_AE18_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_AE18_IS_GPIO
#endif 

#define BALL_AC17 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_AC17_IS_GPIO
#define BALL_AC17_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AC17_IS_GPIO
#endif 

#define BALL_AC18 PAD_PCM2_CE_N
#define PAD_PCM2_CE_N 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_AC18_IS_GPIO
#endif 

#define BALL_AD17 PAD_PCM2_CD_N
#define PAD_PCM2_CD_N 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_AD17_IS_GPIO
#define BALL_AD17_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO BALL_AD17_IS_GPIO
#endif 

#define BALL_AB23 PAD_PCM_WE_N
#define PAD_PCM_WE_N 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AB23_IS_GPIO
#endif 

#define BALL_AG18 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AG18_IS_GPIO
#define BALL_AG18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_AG18_IS_GPIO
#endif 

#define BALL_Y28 PAD_PCM_RESET
#define PAD_PCM_RESET 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_Y28_IS_GPIO
#define BALL_Y28_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_Y28_IS_GPIO
#endif 

#define BALL_AG20 PAD_PCM_REG_N
#define PAD_PCM_REG_N 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AG20_IS_GPIO
#define BALL_AG20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AG20_IS_GPIO
#endif 

#define BALL_AC23 PAD_PCM_OE_N
#define PAD_PCM_OE_N 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AC23_IS_GPIO
#endif 

#define BALL_AG21 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_AG21_IS_GPIO
#define BALL_AG21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AG21_IS_GPIO
#endif 

#define BALL_AD22 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_AD22_IS_GPIO
#define BALL_AD22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AD22_IS_GPIO
#endif 

#define BALL_AC25 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_AC25_IS_GPIO
#define BALL_AC25_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AC25_IS_GPIO
#endif 

#define BALL_AD23 PAD_PCM_CE_N
#define PAD_PCM_CE_N 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_AD23_IS_GPIO
#define BALL_AD23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AD23_IS_GPIO
#endif 

#define BALL_AG19 PAD_PCM_CD_N
#define PAD_PCM_CD_N 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_AG19_IS_GPIO
#define BALL_AG19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AG19_IS_GPIO
#endif 

#define BALL_AF22 PAD_PCM_D7
#define PAD_PCM_D7 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AF22_IS_GPIO
#define BALL_AF22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AF22_IS_GPIO
#endif 

#define BALL_W27 PAD_PCM_D6
#define PAD_PCM_D6 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_W27_IS_GPIO
#define BALL_W27_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_W27_IS_GPIO
#endif 

#define BALL_W28 PAD_PCM_D5
#define PAD_PCM_D5 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_W28_IS_GPIO
#define BALL_W28_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_W28_IS_GPIO
#endif 

#define BALL_Y27 PAD_PCM_D4
#define PAD_PCM_D4 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_Y27_IS_GPIO
#define BALL_Y27_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_Y27_IS_GPIO
#endif 

#define BALL_Y26 PAD_PCM_D3
#define PAD_PCM_D3 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_Y26_IS_GPIO
#define BALL_Y26_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_Y26_IS_GPIO
#endif 

#define BALL_AH22 PAD_PCM_D2
#define PAD_PCM_D2 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AH22_IS_GPIO
#define BALL_AH22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AH22_IS_GPIO
#endif 

#define BALL_AH21 PAD_PCM_D1
#define PAD_PCM_D1 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AH21_IS_GPIO
#define BALL_AH21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AH21_IS_GPIO
#endif 

#define BALL_AE23 PAD_PCM_D0
#define PAD_PCM_D0 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_AE23_IS_GPIO
#endif 

#define BALL_AC24 PAD_PCM_A14
#define PAD_PCM_A14 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AC24_IS_GPIO
#define BALL_AC24_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AC24_IS_GPIO
#endif 

#define BALL_AD25 PAD_PCM_A13
#define PAD_PCM_A13 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_AD25_IS_GPIO
#define BALL_AD25_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AD25_IS_GPIO
#endif 

#define BALL_AD24 PAD_PCM_A12
#define PAD_PCM_A12 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_AD24_IS_GPIO
#define BALL_AD24_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AD24_IS_GPIO
#endif 

#define BALL_AB26 PAD_PCM_A11
#define PAD_PCM_A11 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_AB26_IS_GPIO
#define BALL_AB26_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AB26_IS_GPIO
#endif 

#define BALL_AF20 PAD_PCM_A10
#define PAD_PCM_A10 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_AF20_IS_GPIO
#define BALL_AF20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AF20_IS_GPIO
#endif 

#define BALL_AG22 PAD_PCM_A9
#define PAD_PCM_A9 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_AG22_IS_GPIO
#define BALL_AG22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AG22_IS_GPIO
#endif 

#define BALL_AF21 PAD_PCM_A8
#define PAD_PCM_A8 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_AF21_IS_GPIO
#define BALL_AF21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AF21_IS_GPIO
#endif 

#define BALL_AG23 PAD_PCM_A7
#define PAD_PCM_A7 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_AG23_IS_GPIO
#define BALL_AG23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AG23_IS_GPIO
#endif 

#define BALL_AE24 PAD_PCM_A6
#define PAD_PCM_A6 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_AE24_IS_GPIO
#define BALL_AE24_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AE24_IS_GPIO
#endif 

#define BALL_AF23 PAD_PCM_A5
#define PAD_PCM_A5 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_AF23_IS_GPIO
#define BALL_AF23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AF23_IS_GPIO
#endif 

#define BALL_AB27 PAD_PCM_A4
#define PAD_PCM_A4 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_AB27_IS_GPIO
#define BALL_AB27_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AB27_IS_GPIO
#endif 

#define BALL_AA27 PAD_PCM_A3
#define PAD_PCM_A3 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_AA27_IS_GPIO
#define BALL_AA27_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AA27_IS_GPIO
#endif 

#define BALL_AF19 PAD_PCM_A2
#define PAD_PCM_A2 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_AF19_IS_GPIO
#define BALL_AF19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AF19_IS_GPIO
#endif 

#define BALL_AA26 PAD_PCM_A1
#define PAD_PCM_A1 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_AA26_IS_GPIO
#define BALL_AA26_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AA26_IS_GPIO
#endif 

#define BALL_AF18 PAD_PCM_A0
#define PAD_PCM_A0 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_AF18_IS_GPIO
#define BALL_AF18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_AF18_IS_GPIO
#endif 

#define BALL_AC22 PAD_TS0_D7
#define PAD_TS0_D7 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_AC22_IS_GPIO
#define BALL_AC22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AC22_IS_GPIO
#endif 

#define BALL_AE20 PAD_TS0_D6
#define PAD_TS0_D6 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_AE20_IS_GPIO
#define BALL_AE20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AE20_IS_GPIO
#endif 

#define BALL_AD20 PAD_TS0_D5
#define PAD_TS0_D5 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AD20_IS_GPIO
#endif 

#define BALL_AC20 PAD_TS0_D4
#define PAD_TS0_D4 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_AC20_IS_GPIO
#define BALL_AC20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AC20_IS_GPIO
#endif 

#define BALL_AB20 PAD_TS0_D3
#define PAD_TS0_D3 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_AB20_IS_GPIO
#define BALL_AB20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AB20_IS_GPIO
#endif 

#define BALL_AE21 PAD_TS0_D2
#define PAD_TS0_D2 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AE21_IS_GPIO
#endif 

#define BALL_AB19 PAD_TS0_D1
#define PAD_TS0_D1 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AB19_IS_GPIO
#endif 

#define BALL_AD19 PAD_TS0_D0
#define PAD_TS0_D0 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_AD19_IS_GPIO
#define BALL_AD19_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AD19_IS_GPIO
#endif 

#define BALL_AC19 PAD_TS0_VLD
#define PAD_TS0_VLD 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AC19_IS_GPIO
#endif 

#define BALL_AB22 PAD_TS0_SYNC
#define PAD_TS0_SYNC 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AB22_IS_GPIO
#endif 

#define BALL_AB18 PAD_TS0_CLK
#define PAD_TS0_CLK 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AB18_IS_GPIO
#define BALL_AB18_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AB18_IS_GPIO
#endif 

#define BALL_V27 PAD_TS1_D7
#define PAD_TS1_D7 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_V27_IS_GPIO
#define BALL_V27_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_V27_IS_GPIO
#endif 

#define BALL_W26 PAD_TS1_D6
#define PAD_TS1_D6 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_W26_IS_GPIO
#define BALL_W26_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_W26_IS_GPIO
#endif 

#define BALL_U27 PAD_TS1_D5
#define PAD_TS1_D5 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_U27_IS_GPIO
#define BALL_U27_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_U27_IS_GPIO
#endif 

#define BALL_V26 PAD_TS1_D4
#define PAD_TS1_D4 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_V26_IS_GPIO
#define BALL_V26_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_V26_IS_GPIO
#endif 

#define BALL_T27 PAD_TS1_D3
#define PAD_TS1_D3 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_T27_IS_GPIO
#define BALL_T27_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_T27_IS_GPIO
#endif 

#define BALL_R27 PAD_TS1_D2
#define PAD_TS1_D2 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_R27_IS_GPIO
#define BALL_R27_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_R27_IS_GPIO
#endif 

#define BALL_U26 PAD_TS1_D1
#define PAD_TS1_D1 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_U26_IS_GPIO
#define BALL_U26_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_U26_IS_GPIO
#endif 

#define BALL_T28 PAD_TS1_D0
#define PAD_TS1_D0 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_T28_IS_GPIO
#define BALL_T28_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_T28_IS_GPIO
#endif 

#define BALL_T26 PAD_TS1_VLD
#define PAD_TS1_VLD 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_T26_IS_GPIO
#define BALL_T26_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_T26_IS_GPIO
#endif 

#define BALL_R28 PAD_TS1_SYNC
#define PAD_TS1_SYNC 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_R28_IS_GPIO
#define BALL_R28_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_R28_IS_GPIO
#endif 

#define BALL_R26 PAD_TS1_CLK
#define PAD_TS1_CLK 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_R26_IS_GPIO
#define BALL_R26_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_R26_IS_GPIO
#endif 

#define BALL_AB5 PAD_MICIN0
#define PAD_MICIN0 197
#define GPIO_PAD_197 GPIO196
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif 
#ifndef PAD_MICIN0_IS_GPIO
#define PAD_MICIN0_IS_GPIO BALL_AB5_IS_GPIO
#endif 

#define BALL_AB6 PAD_PAD_MICCM0
#define PAD_PAD_MICCM0 198
#define GPIO_PAD_198 GPIO197
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif 
#ifndef PAD_PAD_MICCM0_IS_GPIO
#define PAD_PAD_MICCM0_IS_GPIO BALL_AB6_IS_GPIO
#endif

#define BALL_AA5 PAD_MICIN1
#define PAD_MICIN1 199
#define GPIO_PAD_199 GPIO198
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif 
#ifndef PAD_MICIN1_IS_GPIO
#define PAD_MICIN1_IS_GPIO BALL_AA5_IS_GPIO
#endif 

#define BALL_AA6 PAD_MICCM1
#define PAD_MICCM1 200
#define GPIO_PAD_200 GPIO199
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif 
#ifndef PAD_MICCM1_IS_GPIO
#define PAD_MICCM1_IS_GPIO BALL_AA6_IS_GPIO
#endif

#define BALL_W2 PAD_RIN0P
#define PAD_RIN0P 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_W2_IS_GPIO
#define BALL_W2_IS_GPIO 0
#endif
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO BALL_W2_IS_GPIO
#endif

#define BALL_V2 PAD_GIN0P
#define PAD_GIN0P 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_V2_IS_GPIO
#define BALL_V2_IS_GPIO 0
#endif
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO BALL_V2_IS_GPIO
#endif

// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_M7632

#endif /* _MT5871IYYTYY_H_*/
