obj-$(CONFIG_AMAZON_DSP_FRAMEWORK)     += src/adf_log.o
obj-$(CONFIG_AMAZON_DSP_FRAMEWORK)     += src/adf_ringbuf.o
obj-$(CONFIG_AMAZON_DSP_FRAMEWORK)     += src/adf_debug.o

ccflags-$(CONFIG_AMAZON_DSP_FRAMEWORK) += -I$(srctree)/$(src)/include
